### ISSUE TITLE
Znpcs not working with command ob gui and ob join!

### ISSUE THREAD

**Issue by MasterHKOG** [MrMarL/OneBlock#25]
[21:35:54 WARN]: [ServersNPC] Task #7612 for ServersNPC v4.8 generated an exception
org.bukkit.command.CommandException: Unhandled exception executing command 'ob' in plugin Oneblock v1.2.5
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:1001) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:1114) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at znpcs-4.8.jar/io.github.gonalez.znpcs.npc.NPCAction$ActionType$2.run(NPCAction.java:76) ~[znpcs-4.8.jar:?]
        at znpcs-4.8.jar/io.github.gonalez.znpcs.npc.NPCAction.run(NPCAction.java:56) ~[znpcs-4.8.jar:?]
        at znpcs-4.8.jar/io.github.gonalez.znpcs.user.ZUser$ZNPCSocketDecoder.lambda$decode$1(ZUser.java:137) ~[znpcs-4.8.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1724) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassCastException: class com.destroystokyo.paper.console.TerminalConsoleCommandSender cannot be cast to class org.bukkit.entity.Player (com.destroystokyo.paper.console.TerminalConsoleCommandSender and org.bukkit.entity.Player are in unnamed module of loader java.net.URLClassLoader @41cf53f9)
        at Oneblock-1.2.5.jar/Oneblock.Oneblock.onCommand(Oneblock.java:685) ~[Oneblock-1.2.5.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        ... 14 more

**Comment by MrMarL** [comment]
Judging by the log, the error is that the command intended for the player is executed by the server console. What exactly are you trying to do?
